#include "MicroBit.h"
#include "Buttons.h"

MicroBitPin P16(MICROBIT_ID_IO_P16, MICROBIT_PIN_P16, PIN_CAPABILITY_ALL);
MicroBitButton Button_LeftTurn(MICROBIT_PIN_P16, MICROBIT_ID_IO_P16, MICROBIT_BUTTON_ALL_EVENTS, PullUp);

MicroBitPin P15(MICROBIT_ID_IO_P15, MICROBIT_PIN_P15, PIN_CAPABILITY_ALL);
MicroBitButton Button_RightTurn(MICROBIT_PIN_P15, MICROBIT_ID_IO_P15, MICROBIT_BUTTON_ALL_EVENTS, PullUp);

MicroBitPin P14(MICROBIT_ID_IO_P14, MICROBIT_PIN_P14, PIN_CAPABILITY_ALL);
MicroBitButton Button_Reverse(MICROBIT_PIN_P14, MICROBIT_ID_IO_P14, MICROBIT_BUTTON_ALL_EVENTS, PullUp);

MicroBitPin P13(MICROBIT_ID_IO_P13, MICROBIT_PIN_P13, PIN_CAPABILITY_ALL);
MicroBitButton Button_Forward(MICROBIT_PIN_P13, MICROBIT_ID_IO_P13, MICROBIT_BUTTON_ALL_EVENTS, PullUp);

MicroBitPin P9(MICROBIT_ID_IO_P9, MICROBIT_PIN_P9, PIN_CAPABILITY_ALL);
MicroBitButton Button_Stop(MICROBIT_PIN_P9, MICROBIT_ID_IO_P9, MICROBIT_BUTTON_ALL_EVENTS, PullUp);

MicroBitPin P8(MICROBIT_ID_IO_P8, MICROBIT_PIN_P8, PIN_CAPABILITY_ALL);
MicroBitButton Button_Menu(MICROBIT_PIN_P8, MICROBIT_ID_IO_P8, MICROBIT_BUTTON_ALL_EVENTS, PullUp);

MicroBitPin P5(MICROBIT_ID_IO_P5, MICROBIT_PIN_P5, PIN_CAPABILITY_ALL);
MicroBitButton Button_Play(MICROBIT_PIN_P5, MICROBIT_ID_IO_P5, MICROBIT_BUTTON_ALL_EVENTS, PullUp);